spring:
  data:
    rest:
      base-path: /api
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    platform: h2

logging:
  level:
    org.flywaydb: debug
    
    org.springframework.orm.jpa: debug
    org.springframework.jdbc: debug
    org.springframework.data.jpa: debug
    org.springframework.data.rest: debug
    #org.hibernate: trace
    
    
  #jpa:
    #generate-ddl: false
    #properties.javax.persistence.schema-generation.create-source: metadata
    #properties.javax.persistence.schema-generation.scripts.action: create
    #properties.javax.persistence.schema-generation.scripts.create-target: create.sql
